### ISSUE TITLE
gogo/googleapis has no LICENSE file

### ISSUE THREAD

**Issue by frankfarzan** [gogo/googleapis#1]
I want to use this repo, but it doesn't have a LICENSE file. Is this intentional?

**Comment by awalterschulze** [comment]
No this is not intentional.
Each non-generated file has a license already.
Most are google apache 2.0
I'll make sure to add a LICENSE to the main repo as well.

**Comment by awalterschulze** [comment]
License added

**Comment by frankfarzan** [comment]
Thanks! I think the scripts didn't have a header, so default copyright applies and taints the repo. But IANAL.
