### ISSUE TITLE
add google longrunning and more common-protos

### ISSUE THREAD

**Issue by robinbraemer** [gogo/googleapis#10]
Could you please add goolge's very common LRO?
Proto: https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto

Also one might consider https://github.com/googleapis/api-common-protos as a reference to add more protos to this repo.

**Comment by johanbrandhorst** [comment]
Sure thing, could you submit a PR with the additions?

Thanks.

**Comment by robinbraemer** [comment]
I tried it but I was not able to compile operations.proto. I think it has something to do with the grpc service and the grpc plugin I missed when compiling with protoc.

**Comment by johanbrandhorst** [comment]
What was the error exactly?

**Comment by johanbrandhorst** [comment]
I think this is at least partially fixed. Was there anything left to do here?

**Comment by robinbraemer** [comment]
It was added, thanks!
