### ISSUE TITLE
Please consider new release version

### ISSUE THREAD

**Issue by SamWhited** [gogo/googleapis#18]
Hi all,

Please consider releasing a new version to pull in #17. This will allow projects depending on this library to not incidentally pull in a version of gogo/protobuf that is vulnerable to the "skippy peanut butter" issue.

Thank you for your consideration!

**Comment by johanbrandhorst** [comment]
Done https://github.com/gogo/googleapis/releases/tag/v1.4.1

**Comment by SamWhited** [comment]
Wow, that was fast; thank you!
