### ISSUE TITLE
Please push to Buf Schema Registry

### ISSUE THREAD

**Issue by haosdent** [gogo/googleapis#19]
Hi, dear authors, I saw you have pushed gogo/protobuf to BSR, do you consider push this repo to BSR as well?

**Comment by johanbrandhorst** [comment]
Hi! The copy of gogo/protobuf that is maintained on the BSR (https://buf.build/gogo/protobuf) is actually maintained by Buf, it's not maintained by us Gogo proto maintainers. The gogo protobuf project is not being actively maintained anymore, and we recommend you move away from using it.
