### ISSUE TITLE
Generated types are no longer convertable to golang/protobuf types

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/googleapis#2]
Since https://github.com/google/go-genproto/pull/65 was merged, `google.golang.org/genproto` types have the new `protoc-gen-go` fields:

https://github.com/jadekler/go-genproto/blob/c60d0593e41763b34a56c7ae500acf1d232486e4/googleapis/rpc/status/status.pb.go#L74

```go
type Status struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// A developer-facing error message, which should be in English. Any
	// user-facing error message should be localized and sent in the
	// [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// A list of messages that carry the error details.  There is a common set of
	// message types for APIs to use.
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}
```

This means the generated types in this repo are no longer convertable, i.e. this is no longer possible:

```go
var _ *rpc.Status = (*rpc.Status)(&status.Status{})
```

Will gogoproto be updated (is it already?) to include these fields as well? If so we need to regenerate these types again.

**Comment by johanbrandhorst** [comment]
This is causing trouble for github.com/gogo/status: https://github.com/gogo/status/issues/4

**Comment by awalterschulze** [comment]
Yes gogoprotobuf will be updated.  It is a matter of simply merging the dev branch.
Except for this one issue:

Everything is working on the dev branch, but @dsnet requires a change, which I have started on the swaptypeassert branch

https://github.com/gogo/protobuf/commit/a136767607748c544aeb664a520b577b0aa027a5#r28903874

Unfortunately this fix is breaking somethings.
I haven't had the time to look more deeply into the issue and unfortunately I do not see myself having time in the next month, which I also think is too long to let this issue stand.
So if @dsnet or @johanbrandhorst could fix my naive swapping of the type assert and find the edge cases that are breaking in the tests, then I would be super grateful.

**Comment by johanbrandhorst** [comment]
I won't have any time anytime soon unfortunately :(. Thanks for confirming my suspicions :).

**Comment by dsnet** [comment]
It seems that this breakage is relying on behavior that is not guaranteed. The proto package loosely follows the [Go1 compatibility guidelines](https://golang.org/doc/go1compat) which reserves the right to:
> For the addition of features in later point releases, it may be necessary to add fields to exported structs in the API.

However, perform conversions like this makes the brittle assumption that fields are never added.

Since the intent seems to be having `rpc.Status` and `status.Status` be the same thing, were type aliases perhaps what you wanted instead?

**Comment by johanbrandhorst** [comment]
@dsnet Good point, but I'm not entirely sure what you mean. Are you saying the generated type should use an alias instead or that the gogo/status package should use an alias? gogo/status needs to be able to define its own functionality on the type so I don't think that will work.

**Comment by dsnet** [comment]
If you desire to have the exact same memory layout, but your own methods, then perhaps a type re-declaration will work?
```go
package status 
type Status rpc.Status

func (s *Status) Method()
```

I'll admit, though, that I don't know enough about this code-base to understand why a separate `Status` type is necessary.

**Comment by johanbrandhorst** [comment]
This issue is about converting `protoc-gen-gogo` generated structs to `protoc-gen-go` structs, for ease of use within https://github.com/gogo/status. I think we could _maybe_ use a type re-declaration in gogo/status, but it wouldn't help the underlying issue, since the types will always be different (they're generated to separate files). I agree it's a brittle assumption, and it's not critical, but it would be nice to able to do it again, and I think with GoGo 1.1 it should be possible again.

**Comment by awalterschulze** [comment]
GoGo 1.1 has now been planned.  We finally figured out the problem, I think we are close to a release.

**Comment by dejvissheshi** [comment]
Is the release still close yet?

**Comment by awalterschulze** [comment]
We have released GoGo 1.1.1

**Comment by johanbrandhorst** [comment]
So I take it we need to regenerate these files with GoGo 1.1.1 and make a new release?

**Comment by awalterschulze** [comment]
Ah yes good point.
Are you up for it?

**Comment by johanbrandhorst** [comment]
I suppose so ;)
